/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 spraga.gltf --types 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder016: THREE.Mesh
    Cylinder016_1: THREE.Mesh
  }
  materials: {
    ['2.Apple.001']: THREE.MeshStandardMaterial
    ['Metal.001']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/public/model/AppleCan/spraga.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder016.geometry} material={materials['2.Apple.001']} />
      <mesh geometry={nodes.Cylinder016_1.geometry} material={materials['Metal.001']} />
    </group>
  )
}

useGLTF.preload('/spraga.gltf')
