/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 test.gltf --types 
Author: ForevereQ (https://sketchfab.com/ForevereQ)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/coca-cola-can-can-of-soda-a49763f3d67e4cd1bf7a41319535f4d0
Title: Coca-Cola Can / Can of Soda
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder001_Material_0: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/public/model/CocaCola/test.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.Cylinder001_Material_0.geometry} material={materials.Material} position={[4.48, 544.66, 0.306]} rotation={[-Math.PI / 2, 0, -0.924]} scale={78.803} />
      </group>
    </group>
  )
}

useGLTF.preload('/test.gltf')
